spring:
  profiles:
    active: work-queues,receiver
  rabbitmq:
    host: 118.25.195.112
    port: 5672
    username: guest
    password: guest

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000